export const types = {
  UI_OPEN_MODAL:            '[UI] OPEN_MODAL',
  UI_CLOSE_MODAL:           '[UI] CLOSE_MODAL',

  EVENT_SET_ACTIVE:         '[EVENT] SET_ACTIVE',
  EVENT_ADD_NEW:            '[EVENT] ADD_NEW',
  EVENT_CLEAR_ACTIVE_EVENT: '[EVENT] CLEAR_ACTIVE_EVENT',
  EVENT_UPDATED:            '[EVENT] UPDATED',
  EVENT_DELETED:            '[EVENT] DELETED'
}

